---
title: "Assessments"
description: "Midterm and final course assessmentsfor PSYC 2530"
author: "Matt Crump"
date: '`r paste("Last edited: ", lubridate::today())`'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Assessments}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In the Fall 2022 version of this course there are three course assessments throughout the semester. These assessments take the place of conventional midterms and final exams, and are being developed in collaboration with the class. The instructions for each assessment are posted below. The purpose of the first assessment at the beginning of the course is for students to identify and set goals. The purpose of the second assessment in the middle of the semester is to reflect on progress so far, re-evaluate and refine, and make adjustments if necessary for the rest of the semester. The final assessment occurs during the final exam period, and provides an opportunity to reflect upon progress made toward goals in the course.

## Assessment 1 

The purpose of this assessment is to identify and set goals for the course.

Instructions: This assessment has already been completed in class. If you have not yet completed the assessment, then please do so and submit it on Blackboard.

Name:
Date:

1. Identify 3 to 5 goals you have for after your degree

2. Identify 3 to 5 goals you have while you complete your degree

3. Identify 3 to 5 goals you have for this semester

4. Identify 3 to 5 goals you have for this course.

5. What skills do you want to improve on in this course?

6. What are your stretch goals? These, are things you would try to accomplish if you find the time and energy to do these goals in this course, this semester.

7. What grade do you want at the end of this course?

## Midterm Assessment (October 17th)

The structure of this assessment will be discussed in class, and eventually posted here when it is finalized.

TBD

## Final Assessment (Final Exam Period)

The structure of this assessment will be discussed in class, and eventually posted here when it is finalized.


TBD
