---
title: "General Assignments"
description: "A list of general assignments for PSYC 2530"
author: "Matt Crump"
date: '`r paste("Last edited: ", lubridate::today())`'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{General Assignments}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


The following assignments are not associated with a specific learning module. Instead, these more general assignments that engage you in various aspects of cognitive psychology. See the general assignment section on Blackboard for information about submitting and due dates.

## Write a Short Answer question

Write your own short answer question (appropriate for a midterm or final exam) that would test a concept from any aspect of Cognitive Psychology covered in this course. Then, provide an answer to the question in at least 100 words that could be used as an example of a high-quality answer that should receive full marks.

Submit the wording for your question and your answer. This assignment is worth 5 points. It will be graded pass/fail.


Example:

To give an example, the following could appear as a short answer question on an exam testing content in the memory I chapter.

Question: How does the multi-store model (Atkinson and Shiffrin) explain the recency effect, and why is it unable to explain the long-term recency effect?

Answer: The multi-store model uses a short-term rehearsal buffer to explain the recency effect. The recency effect is the finding that words at the end of a list are typically recalled better than words in the middle of the list. According to the model, the words at the end of list are being actively rehearsed in the short-term rehearsal buffer. As result, all of the words in the buffer are available when participants recall the words. Specifically, during the recall phase, participants may simply write down the words they are rehearsing. As a result, recall memory is higher for the words at the end of the list (which are in the buffer and recalled immediately), compared to words in the middle of the list, which are likely not in the rehearsal buffer. The long-term recency effect occurs when a long delay intervenes between the encoding phase and recall phase. Over this period of time it is likely that any short-term rehearsal buffer no longer contains any words from the encoding phase (i.e., participants stop actively rehearsing words). Nevertheless, the long-term recency effect shows better recall memory for words at the end of a list compared to words from the middle of the list. This finding is not well explained by the concept of a short-term rehearsal process, because people are assumed to have ceased rehearsing well-before the final recall test.

## Choose your own adventure

This is a choose your own adventure assignment worth 5 points. 

1. Do anything you want (e.g., that is interesting to you, motivates you etc.) that engages you with the cognitive psychology literature.

2. Show me what you did by submitting evidence of your work to this assignment.

3. Additionally, provide a brief argument explaining why this activity should be worth 5 points toward your grade in this course.

Additional clarification:

You could think of this as an opportunity to create your own assignment for yourself, and then do it. You should be doing something for this course that you have not done before. For example, don't tell me the that you did something a while ago, and then try to get credit for it.
There are many things that you could do to engage yourself with the field of cognitive psychology. Importantly, you won't get credit for being a person with cognition. For example, if you say that you had thoughts in your head yesterday, and that involves cognition, I won't give you points. But, if you said you wondered about your inner voice and how that works, so you read a paper from the literature on the cognition of inner voice processes, and then summarized what you read in a short abstract so that you could remember the article...that would count for course credit.

## React to a highly cited paper

In at least 250 words, your task is to read and write a reaction to a highly cited paper in Cognitive Psychology. 

1. Choose your paper from the appendix found at the end of the paper below. This appendix lists many highly cited papers in Cognitive Psychology. 

Cho, K. W., Tse, C. S., & Neely, J. H. (2012). Citation rates for experimental psychology articles published between 1950 and 2004: Top-cited articles in behavioral cognitive psychology. Memory & cognition, 40(7), 1132-1161.

2.Obtain the .pdf and read it

3. Write your reaction to the paper in at least 250 words, and submit it here.

4. Also submit the pdf, link, or citation to your chosen paper.

Tips:

Part of this assignment involves obtaining your chosen paper. I recommend that you copy the citation for the paper into Google Scholar to find out if there is a pdf available. If not, then attempt to download the paper through the Brooklyn College library. You could put the title of the paper into ONE search and see if it finds an online version, or search for the journal containing the article, and find it through an e-journal portal.

This assignment is worth 5 points.
