---
title: "Contribute for Extra Credit"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Contribute for Extra Credit}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Background

This page describes ways in which you can contribute to this course. There are different kinds and levels of contribution, and each come along with associated credits, from extra-credit in the course, official acknowledgment as a course contributor, and even potential authorship of course materials.

Before I describe some of the options available to you, I briefly overview the philosophy and general arrangements behind this course. First, I have chosen to create all of the course materials as an Open Educational Resource (OER). I also license all of the materials under a creative commons license (CC-BY 4.0). This license essentially permits others to use these resources, edit them, remix, and/or reuse them (and provide citations and credit to original authors).

At the present moment (Fall 2020) the main course materials exist as a Github Repository <https://github.com/CrumpLab/psyc7709Lab>, which contains R source code that generates all of the content in this website. The major course documents are .Rmd files located in the vignettes folder. The youtube videos are also CC licensed, and linked to in the various course documents. At the end of this course (December 2020), I will take additional steps to give these materials a proper title, publish them-- likely on open-science framework--, and version them with a digital object identifier (DOI). This will provide a clear way for others to cite the work, and also provide an additional way to share the materials. Note, any student contributions to the course materials will be acknowledged, and substantial contributions would lead to recognition as an author of the materials.

In summary, I have recently advocated that students consider their work in terms of developing a portfolio (see Crump, 2019 <https://www.nature.com/articles/s41562-019-0689-0>). To facilitate this, I look for ways that students can contribute to their while accomplishing their course work. In this case, if you take up the extra credit opportunity, you will be officially contributing to the Github repository for this course, and this could be an item on your portfolio that you could show other people.

## General Instructions

The basic extra credit opportunity is for 5 points and is also an opportunity to learn about Github pull requests. Here is the general process:

1. You need to fork a copy of the Github repo for this course, located here: <https://github.com/CrumpLab/psyc7709Lab>
 - You can click the little fork button on the top right in your browser, this will automatically make a copy of the repository in your Github account.
 - You can add this as a repository through Github Desktop to create a local copy on your computer. 
2. Next, you need to make a contribution, that means changing/editing the files. For example, the .Rmd files for each lab are located in the `vignettes` folder. You could open one up, edit it, and then commit your changes.
  - at this point your copy is different from mine, and you will be requesting that I accept your changes, to do this you will submit a pull request.
3. Submit your pull request to me. If I approve your suggested changes then you will have successfully completed the basic extra credit opportunity, and you will receive 5 extra points.

### Options for Extra Credit

I am open to multiple forms of contribution. 

1. Fix a typo, a coding error, or other small change (5 extra credit points). 
  - you will also be recorded in the Github repository as contributing to the course material.
  - I will acknowledge you as a student contributor in the final published version of this course material
 
---  

Everything after option 1 involves more substantial contribution, and the role of points becomes more unclear to me, and potentially up for negotiation.

2. Substantial copy-editing. This would involve fixing more than a typo, but not really changing the conceptual structure or content of the lab. If I accepted pull request like this I would find a way to credit you as a student reviewer in the final course materials.

3. Rewrite a whole lab your way, or write an entirely different lab on a topic that could have been a lab in this course. You've all seen what the labs look like, the existing .Rmds are in the `vignettes` folder, so you can see clear examples of the structure I am using. If you contributed at this level I would figure out ways to include you as an author on the materials.

4. There are many levels of contribution between fixing a typo and writing your version of this entire course. I'm open to suggestions. In my opinion, if you wrote this entire course you should obviously get an A+. I also think that if you wrote half of this course you should get an A+ (say instead of doing all of the assignments). I'm not sure where that line is, but I know the process and act of creating instructional materials is a great way to demonstrate your command over the materials. Basically, I'm open to all sorts of suggestions, and I will probably add to this list and to clarify additional opportunities.
  

  








