---
title: "Syllabus"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

### PSYC 2530 – Introduction to Cognitive Psychology

Fall 2022

Section: MW3 7066

Time: 3:40pm - 4:55pm, Monday and Wednesday

Location: 1127 IH (Ingersoll Hall)

Office Hours: TBA (zoom link posted on Blackboard)

Instructor:  Dr. Matthew Crump

Email: mcrump@brooklyn.cuny.edu (please put PSYC 2530 in subject line)

## Course Description

PSYC 2530 Introduction to Cognitive Psychology

3 hours; 3 credits

This course will provide an introductory overview of basic concepts in cognitive psychology such as memory, attention, perception, problem solving, decision-making, language and imagery. Experimental findings and proposed models will be discussed for each topic.

**Course objectives**: develop the following skills in relation to content learning objectives in 2530:

|Goal|Learning Outcome|
|----|-----|
| 1. Exposure to breadth of theory and data across major domains of cognition (listed above) | Students will demonstrate ability to identify and describe domain-specific theories and phenomena|
| 2. Understanding deduction from theory, which requires an understanding of the assumptions of a theory and how they combine to force a clear prediction.|Students will demonstrate the ability to describe in written format the assumptions of a domain-specific theory along to show how the theory demands a prediction.|
| 3. Understanding experimental design | Students will demonstrate working knowledge of the elements of particular experimental designs that create opportunity to test a theoretical idea |
| 4. Understanding patterns in data | Students will demonstrate the ability to interpret tables and figures, including the pattern for how a dependent measure changes across the levels/conditions of the independent variable |
| 5. Understanding inference from results to theory |Students will demonstrate the ability to form an inference about an observed result, and display the ability to evaluate whether or not a result conforms to a prediction made by a theory in cognitive psychology |


## Course Materials

All of the course materials will be available in a timely fashion on this course website and/or posted on blackboard.

Link to the course website:
<https://www.crumplab.com/cognition/>


## Course Structure

There are 15 total weeks. Weekly learning modules cover different topics in cognitive psychology. Assessment weeks are interspersed across the semester. Students are expected to complete the learning modules and assessments which provide opportunities to earn up to 100 points toward a final grade.

This is an **in-person** class, and students are expected to attend class sessions on a routine basis.

### Learning module structure

Weekly learning modules include three components to encourage engagement with the domain of cognitive psychology in different ways.

**READ**: Modules have assigned readings from textbook chapters or primary research articles. Readings are freely available and posted on blackboard or the course website. Student are strongly encouraged to read assigned material before classes where the material is discussed.

**CLASS and WATCH/LISTEN**: Modules usually involve two class meetings designed to engage students in the module topic. Classes will involve a mixture of lectures and other activities. *Note: a previous version of this course was taught asynchronously online which involved the creation of mini-lecture videos for each module. These videos will remain on the course website for students to use as supplemental resource. Slide decks used in the lecture will be posted on the course website.*

**ENGAGE**: Modules include assignments for students to engage with course material. Assignments for each module will vary, and there will be some flexibility for students to choose the assignments they complete.


## Course Schedule

```{r, message=FALSE, warning=FALSE, echo=FALSE, eval=TRUE}
#library(data.table)
library(readxl)
Lectures <- read_excel("Fall_2022_schedule.xlsx", sheet = 1, col_names = TRUE, col_types = NULL, na = "", skip = 0)
Lectures$Week <- as.character(Lectures$Week)
Lectures[is.na(Lectures)] <- " "
#Lectures <- fread("Lectures.csv")
knitr::kable(Lectures)

```

## Assignments, Assessments, and Grading

There are multiple ways for students to engage with course materials and achieve their desired grade. Students are encouraged to choose the assignments that work best for them. Major course assessments that occur throughout the semester are designed to help students set and achieve their own goals for engaging in course content.

### Assignments

Each weekly module will contain two or more assignment opportunities. In general, quizzes are worth 2.5 points and other assignments are worth 5 points. **Students are strongly encouraged to complete at least one assignment per module**. Students can complete as many quizzes or assignments as they want, for a maximum of 75 points toward their final grade.

In collaboration with the instructor, students follow a process of self-assessment to recommend how many points should be awarded for their own assignments (not including quizzes). The self-assessment process is used as a guide toward goal setting and achievement in the course.

In addition to the weekly assignments, which focus on the details of module content, there are opportunities to complete more general assignments. These are listed on their own tab within blackboard.

### Discussion Boards

There will be opportunity to gain points through participation in discussion boards on Blackboard. See instructions on blackboard for individual discussion boards.

### Assessments

There are three major assessments throughout the semester culminating in a final assessment conducted during final exam week. These assessments are used as an aid toward goal-setting and achievement in the course. The first two assessments focus on goal-setting and goal refinement with respect to engaging in course material. The final assessment focuses on goal-achievement, and feedback with respect to engaging in course material. Unless otherwise stated all major course assessments are conducted in person during regular class time (or during the scheduled final exam period). Bring a pen or pencil.

### Points and letter grades

| Assignment |  Points| Total|
|:----------|--------:|-------:|
| 12 Weekly Modules | 5+ | up to 75|
| Assessment 1 | 5 | 5 |
| Assessment 2 | 10 | 10 |
| Final Assessment | 10  | 10|
|||100|

Percentage grades are converted to letter grades according to the following rubric.

|Letter grade|Range|
|:--|:--|
|A+	|96.67-100|
|A	|93.33-96.66|
|A-	|90-93.32|
|B+	|86.67-89.99|
|B	|83.33-86.66|
|B-	|80-83.32|
|C+	|76.67-79.99|
|C	|73-76.66|
|C-	|70-72.99|
|D+	|66.67-69.99|
|D	|63.33-66.66|
|D-	|60-63.32|
|F	|0-59.99|

## Attendance

Students are expected to attend and participate in each class. An attendance record will be taken each class. Although there are no specific points for attendance, students will use their attendance and participation record to justify their self-assessments and final grade in the course.

## Honors Projects

It is possible to complete an honors project and receive honors credit for this course. Please see the [honors project page](https://crumplab.com/cognition/articles/honors/honors.html) for more information.

## Course Policies

### Due dates

Due dates are suggestions for completing coursework on a weekly basis. You may be able to work ahead, but you are not encouraged to fall behind.

You should email me if you have an exceptional circumstance preventing you from taking an assessment during an assessment week.

### Changes to the syllabus

The syllabus may be updated for clarity or to make adjustments for pedagogical purposes. The most current version of the syllabus is always available from the course website.

### Individual versus group work

**The default assumption is that all assigned work is individual work. Therefore, you should complete all coursework by yourself.** Make sure you understand the University's policy on Academic Integrity, described below. Any assignment that is not an individual assignment will be clearly labeled.

### Missing an Exam

In the event of an emergency, contact me as soon as possible. If you are missing an exam for religious reasons refer to the state law regarding non-attendance because of religious beliefs noted in the front matter of the Undergraduate Bulletin and Graduate Bulletin. These may be found on the Academic Calendars, Course Schedules, and Bulletins page of the Registrar’s website. See also the student bereavement policy at <http://www.brooklyn.cuny.edu/web/about/initiatives/policies/bereavement.php>.

---

### Accessibility

In order to receive disability-related academic accommodations students must first be registered with the Center for Student Disability Services. Students who have a documented disability or suspect they may have a disability are invited to set up an appointment with the Director of the Center for Student Disability Services, at 718-951-5538. If you have already registered with the Center for Student Disability Services, please provide your professor with the course accommodation form and discuss your specific accommodation with him/her.

---

### Email Correspondence

I will regularly use e-mail via blackboard to send out announcements, changes in the syllabus, reminders about tests or due dates etc. It is your responsibility to check e-mail regularly to keep up-to-date with these announcements. I will use the e-mail address you have listed with the College. Therefore, please make sure that this is indeed the correct address.

If you have questions please email me:

1. put PSYC 2530 in your subject line
2. email me at: mcrump@brooklyn.cuny.edu

### General Help with Research and Writing

The Library maintains a collection of links to sites that can assist you with proper citation format and paraphrasing and quoting other authors at [Research & Writing Help](https://library.brooklyn.cuny.edu/resources/?service=research-help).  The Learning Center has writing tutors available to help you with your writing [http://lc.brooklyn.cuny.edu/](http://lc.brooklyn.cuny.edu/).

The best learning is done in conversation with others, whether they are people—classmates, teachers, friends—or texts—books, articles, essays, poems, films etc. It should not be a solitary process. However, the assignments that you hand in for this course must be done on your own, should represent your own thinking, and should be original work that you have done for this particular course. A good way to balance these two seemingly contradictory approaches (collaborative learning and original individually-produced work) without knowingly—or, even unwittingly—resorting to plagiarism or other forms of academic misconduct is to learn and meticulously observe the rules for citing the work of others (this could be the great point your roommate made that you used in your paper, it could be a well-turned phrase from an academic essay, or it could be anything in between). It is your responsibility to learn what constitutes plagiarism and the correct rules for citing sources—read the information on the following website carefully: [http://www.brooklyn.cuny.edu/bc/policies/](http://www.brooklyn.cuny.edu/bc/policies/). The bottom line is: passing off anyone’s words or ideas as your own for any reason whatsoever is plagiarism.

## Violations of Academic integrity

It is the responsibility of each student to understand and act in accordance with the University's policy on Academic Integrity, described below.

### University’s policy on Academic Integrity

The faculty and administration of Brooklyn College support an environment free from cheating and plagiarism. Each student is responsible for being aware of what constitutes cheating and plagiarism and for avoiding both. The complete text of the CUNY Academic Integrity Policy and the Brooklyn College procedure for implementing that policy can be found at [this site](http://www.brooklyn.cuny.edu/web/about/initiatives.php). If a faculty member suspects a violation of academic integrity and, upon investigation, confirms that violation, or if the student admits the violation, the faculty member MUST report the violation.

### FYI on cheating etc.

Remember, you are responsible for not cheating or violating CUNY's  [Academic Integrity Policy](http://www.cuny.edu/about/administration/offices/legal-affairs/policies-resources/academic-integrity-policy/). You are responsible for understanding that policy, and for conducting yourself in a manner such that you do not violate the policy.

The above link lists many examples of cheating and plagiarism that are not allowed. There are many more specific acts that you should NOT do. Here is an additional list of activities that will be sufficient cause for immediate failure in the course.

- Do not take pictures of exam or quiz questions and share them with other students
- Do not give other students answers during an exam or quiz, or any other assignment that is an individual assignment
- Do not copy work from another source and submit it as your own
- Do not copy and paste text from the internet and submit it as your own words
- Do not copy and paste text and slightly alter wording to pass the work off as your own
- Do not hire someone else to do the coursework for you
- Do not copy and paste text into a paraphrasing app, and then submit the output of the paraphrasing app as your own work
- Do not copy random words from the internet that have nothing to do with the assignment and submit them as your own work.
- Do not work on individual assignments with other students, share answers or other material, and then all hand in versions of the same thing that are slightly different.
- Do not plagiarize yourself by submitting work that you have previously completed in another class.

### Mandate to report violations

If a faculty member suspects a violation of academic integrity and, upon investigation, confirms that violation, or if the student admits the violation, the faculty member MUST report the violation. Students should be aware that faculty may use plagiarism detection software.

There is no excuse for cheating. Students who are caught cheating may receive a failing grade for the entire course. All students who violate the academic integrity will receive a Faculty Action Report, which will go on their personal file at the Academic Integrity Office.

## FAQ

If you have questions about the syllabus, please create a thread on the discussion board for this course on Blackboard.


