---
title: "Syllabus"
author: 'Matthew Crump'
format: 
  html: default
  pdf: default
---

### PSYC 2530 -- Introduction to Cognitive Psychology

**This syllabus is the Fall 2023 syllabus. It may be revised across the semester to address course needs.**

Fall 2023

Section: NET 3285

Time/Location: Asynchronous Online

Office Hours: TBA (zoom link posted on Blackboard)

Instructor: [Dr. Matthew Crump](https://www.crumplab.com)

Email: mcrump\@brooklyn.cuny.edu (please put PSYC 2530 in subject line)

## Course Description

PSYC 2530 Introduction to Cognitive Psychology

3 hours; 3 credits

This course will provide an introductory overview of basic concepts in cognitive psychology such as memory, attention, perception, problem solving, decision-making, language and imagery. Experimental findings and proposed models will be discussed for each topic.

**Course objectives**: develop the following skills in relation to content learning objectives in 2530:

| Goal                                                                                                                                                      | Learning Outcome                                                                                                                                                                                                   |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1\. Exposure to breadth of theory and data across major domains of cognition (listed above)                                                               | Students will demonstrate ability to identify and describe domain-specific theories and phenomena                                                                                                                  |
| 2\. Understanding deduction from theory, which requires an understanding of the assumptions of a theory and how they combine to force a clear prediction. | Students will demonstrate the ability to describe in written format the assumptions of a domain-specific theory along to show how the theory demands a prediction.                                                 |
| 3\. Understanding experimental design                                                                                                                     | Students will demonstrate working knowledge of the elements of particular experimental designs that create opportunity to test a theoretical idea                                                                  |
| 4\. Understanding patterns in data                                                                                                                        | Students will demonstrate the ability to interpret tables and figures, including the pattern for how a dependent measure changes across the levels/conditions of the independent variable                          |
| 5\. Understanding inference from results to theory                                                                                                        | Students will demonstrate the ability to form an inference about an observed result, and display the ability to evaluate whether or not a result conforms to a prediction made by a theory in cognitive psychology |

## Course Materials

Course materials will be available from this course website or posted on blackboard.

Link to the course website: <https://www.crumplab.com/cognition/>

## Blackboard

Blackboard will be used for course announcements, discussion boards, and for students to submit their assignments.

**It is essential that students make sure their email address is correctly registered with Blackboard. Blackboard announcements will be sent to students at their registered email address.**

## Course Structure

This is an asynchronous online course consisting of weekly learning modules and assessments. There are a total of fifteen weeks in this course. Thirteen weeks involve cognitive psychology learning modules. The remaining two weeks assess course engagement goals. Learning modules and assessments provide opportunities for students to earn up to 100 points toward their final grade (see @sec-points for translation to letter grades). 

There are numerous optional assignments, providing students with various opportunities to accrue points. Students are encouraged to select assignments that they find engaging and interesting.

### Learning module structure

Weekly learning modules include three components to encourage engagement with the domain of cognitive psychology.

**READ**: Modules have assigned readings from textbook chapters or primary research articles. Readings are freely available and posted on blackboard or the course website. 

**WATCH/LISTEN**:  Modules will have mini-lecture videos with overviews of the readings. The videos and slides will be posted on the course website. 

**ENGAGE**: Modules include assignments for students to engage with course material. Assignments vary and there is flexibility for students to choose which assignments they complete.

## Course Schedule

```{r, message=FALSE, warning=FALSE, echo=FALSE, eval=TRUE}
#library(data.table)
library(readxl)
Lectures <- read_excel("Fall_2023_schedule.xlsx", sheet = 1, col_names = TRUE, col_types = NULL, na = "", skip = 0)
Lectures$Week <- as.character(Lectures$Week)
Lectures[is.na(Lectures)] <- " "
#Lectures <- fread("Lectures.csv")
knitr::kable(Lectures)

```

## Assignments, Assessments, and Grading

There are multiple ways for students to engage with course materials and achieve their desired grade. Students are encouraged to choose the assignments that work best for them. Major course assessments that occur throughout the semester are designed to help students set and achieve their own goals for engaging in course content.

### Assignments

Each weekly module contains two or more assignment opportunities. In general, quizzes are worth 2.5 points, and other assignments are worth 5 points. 

Unless otherwise noted, students can choose which quizzes or assignments to complete for a given module. Across the semester, students can complete as many quizzes or assignments as they want, for a maximum of 85 points toward their final grade. 

In addition to the weekly assignments, which focus on the details of module content, there are opportunities to complete other more general assignments. These general assignments are listed on the website and have their own tab on Blackboard.

In collaboration with the instructor, students follow a process of self-assessment to recommend how many points should be awarded for their own assignments (excluding quizzes). The self-assessment process is used as a guide towards goal setting and achievement in the course.

### Discussion Boards

There will be opportunity to gain points through participation in discussion boards on Blackboard. See instructions on Blackboard for individual discussion boards.

### Assessments

There are three assessments throughout the semester culminating in a final assessment conducted during final exam week. Each assessment is worth five points, for a total of 15 points.

The first two assessments focus on goal-setting and goal refinement with respect to engaging in course material. The final assessment focuses on goal achievement and feedback with respect to engaging in course material. 

### Points and letter grades {#sec-points}

| Assignment        | Points |    Total |
|:------------------|-------:|---------:|
| Weekly coursework |  2.5-5+ | up to 85 |
| Assessment 1      |      5 |        5 |
| Assessment 2      |      5 |        5 |
| Final Assessment  |      5 |        5 |
|                   |        |      100 |

Percentage grades are converted to letter grades according to the following rubric.

| Letter grade | Range       |
|:-------------|:------------|
| A+           | 96.67-100   |
| A            | 93.33-96.66 |
| A-           | 90-93.32    |
| B+           | 86.67-89.99 |
| B            | 83.33-86.66 |
| B-           | 80-83.32    |
| C+           | 76.67-79.99 |
| C            | 73-76.66    |
| C-           | 70-72.99    |
| D+           | 66.67-69.99 |
| D            | 63.33-66.66 |
| D-           | 60-63.32    |
| F            | 0-59.99     |

### Lateness and due dates

This is an asynchronous course that allows students some flexibility to work on the material according to your own schedule. However, there are also due dates, and expectations that students will be completing coursework on a weekly basis. Students may be able to work ahead, but they are not encouraged to fall behind.

Each of the assignments, quizzes, and assessments will be posted with a due date. A quiz or assignment will be open for a week-long period, and the work is expected to be completed within the assigned time frame. Late assignments may not be graded.

If a student misses an assignment, it is possible to make up the points for the assignment in a later learning module by completing an extra assignment.

## Assignment selection limitations

Most assignments in this course are optional and students can pick and choose which ones they complete across the semester. Throughout the semester additional assignments or ways of getting points may become available as they are developed. Students are encouraged to pick assignments that they find the most engaging, interesting, and challenging.

**It is important that students demonstrate their engagement with the course across the whole semester.** This will be reflected in students having completed coursework on a weekly basis throughout the semester.

It is not possible to wait until the end of the course and submit as many things as possible. Students are limited to accruing no more than 20 points a weeks. 

The important point is to engage with the content and get something out of it. If you are engaging with this course every week and you can show this to me, then please keep doing this and don't worry as much about the point system (as you will no doubt get all the points you need).

## Honors Projects

Any student may complete an honors project and receive honors credit for this course. Please see the [honors project page](https://crumplab.com/cognition/articles/honors/honors.html) for more information.

## Course Policies

### Changes to the syllabus

The syllabus may be updated for clarity or to make adjustments for pedagogical purposes. The most current version of the syllabus is always available from the course website.

### Individual versus group work

All assigned work is individual work unless otherwise stated. **Therefore, students should complete all coursework by themself.** 

Students are required to read, understand, and abide by the University's policy on Academic Integrity (see @sec-integrity). Any assignment that is not an individual assignment will be clearly labeled.

### Using ChatGPT or similar tools in this course

ChatGPT and other similar tools have been trained on a large amount of text from the internet. These tools are capable of generating text that is similar in style to the text the models have been trained on. They are also capable of fabricating complete nonsense. This section describes allowable use cases for this course. This course does not require the use of this software.

1. **If a student uses ChatGPT to complete an assignment, then they are required to explain how the tool was used at the end of the assignment.**

2.  It is okay to explore the technology: how it works, how one might use it as a tool, and the very real issues surrounding this technology for society.

3.  Do not rely on this technology being there for free. 

4.  Passing off work from ChatGPT as your own is a violation of academic integrity that will be taken very seriously (see the academic integrity policy in @sec-integrity). 

**I care about what you have to say, not what ChatGPT has to say.**

It is best to treat ChatGPT like a chaotic assistant that sometimes completes a task up to a desired standard, but other times produces messy, incorrect, and nonsensical results.

Do not trust the accuracy of ChatGPT results. ChatGPT does not produce accurate text. It produces text that may look like it is in a desired style, but that does not mean the text is accurate. ChatGPT will produce text with fabricated "facts" that are not true. ChatGPT will produce references that do not exist. ChatGPT will modify words that critically alter the original meaning of text. Use the tool responsibly.

#### Acceptable use cases

This is not an exhaustive list. If a student thinks the way they used the tool was appropriate, then they can include an explanation of their use case when submitting the assignment.

1. Spelling or grammar checker. I've done this myself and it sometimes helps. It regularly produces suggestions that I don't accept, so be careful.

2. Help turn notes into a paragraph. Give ChatGPT some notes in point form and ask it to turn the points into a paragraph. Then, use the paragraph as a starting point for your own writing process.

3. Summarize something. Ask ChatGPT to summarize text into point form. Be very careful here. ChatGPT will produce bullet points, but they won't necessarily be a good or accurate summary of the input text. Don't trust the results.

4. Ask ChatGPT to generate search terms that can be used to find research on a particular topic.

**Remember, if you use ChatGPT as a tool to complete your assignment, then you are required to explain how you used it in your assignment.**

#### Unacceptable use cases

This is not an exhaustive list of unacceptable use cases that violate academic integrity principles.

1. Submitting an assignment prompt to ChatGPT and handing in ChatGPT's response as your own writing. 

2. Copying another source, having ChatGPT rewrite it to appear different, and then handing the response in as your own writing.

ChatGPT is a new and rapidly changing technology. This syllabus may be updated throughout the semester to respond to unacceptable uses of ChatGPT that violate the acacdemic integrity policy. Changes may include altered modes of assessment.

### Missing an Exam

In the event of an emergency, contact me as soon as possible. If you are missing an exam for religious reasons refer to the state law regarding non-attendance because of religious beliefs noted in the front matter of the Undergraduate Bulletin and Graduate Bulletin. These may be found on the Academic Calendars, Course Schedules, and Bulletins page of the Registrar's website. See also the student bereavement policy at <http://www.brooklyn.cuny.edu/web/about/initiatives/policies/bereavement.php>.

------------------------------------------------------------------------

### Accessibility

In order to receive disability-related academic accommodations students must first be registered with the Center for Student Disability Services. Students who have a documented disability or suspect they may have a disability are invited to set up an appointment with the Director of the Center for Student Disability Services, at 718-951-5538. If you have already registered with the Center for Student Disability Services, please provide your professor with the course accommodation form and discuss your specific accommodation with him/her.

------------------------------------------------------------------------

### Email Correspondence

I will regularly use e-mail via blackboard to send out announcements, changes in the syllabus, reminders about tests or due dates etc. 

It is your responsibility to check e-mail regularly to keep up-to-date with these announcements. I will use the e-mail address you have listed with the College. Therefore, please make sure that this is indeed the correct address.

If you have questions please email me:

1.  put PSYC 2530 in your subject line
2.  email me at: mcrump\@brooklyn.cuny.edu

### General Help with Research and Writing

The Library maintains a collection of links to sites that can assist you with proper citation format and paraphrasing and quoting other authors at [Research & Writing Help](https://library.brooklyn.cuny.edu/resources/?service=research-help). The Learning Center has writing tutors available to help you with your writing <http://lc.brooklyn.cuny.edu/>.

The best learning is done in conversation with others, whether they are people---classmates, teachers, friends---or texts---books, articles, essays, poems, films etc. It should not be a solitary process. However, the assignments that you hand in for this course must be done on your own, should represent your own thinking, and should be original work that you have done for this particular course. A good way to balance these two seemingly contradictory approaches (collaborative learning and original individually-produced work) without knowingly---or, even unwittingly---resorting to plagiarism or other forms of academic misconduct is to learn and meticulously observe the rules for citing the work of others (this could be the great point your roommate made that you used in your paper, it could be a well-turned phrase from an academic essay, or it could be anything in between). It is your responsibility to learn what constitutes plagiarism and the correct rules for citing sources---read the information on the following website carefully: <http://www.brooklyn.cuny.edu/bc/policies/>. The bottom line is: passing off anyone's words or ideas as your own for any reason whatsoever is plagiarism.

## Violations of Academic integrity {#sec-integrity}

It is the responsibility of each student to understand and act in accordance with the University's policy on Academic Integrity, described below.

### University's policy on Academic Integrity

The faculty and administration of Brooklyn College support an environment free from cheating and plagiarism. Each student is responsible for being aware of what constitutes cheating and plagiarism and for avoiding both. The complete text of the CUNY Academic Integrity Policy and the Brooklyn College procedure for implementing that policy can be found at [this site](http://www.brooklyn.cuny.edu/web/about/initiatives.php). If a faculty member suspects a violation of academic integrity and, upon investigation, confirms that violation, or if the student admits the violation, the faculty member MUST report the violation.

### Commitment to uphold standards of academic integrity

The most important thing you can do in this course is complete the work with integrity. This means engaging with the course content and doing the work yourself. The more that you do this, the more you will get out of the course. 

You are responsible for reading and understanding the CUNY's [Academic Integrity Policy](http://www.cuny.edu/about/administration/offices/legal-affairs/policies-resources/academic-integrity-policy/). You are responsible maintaining your own academic integrity in this course. By enrolling in this course, and by participating in it, you are committed to upholding these standards. 

### Examples of academic integrity violations

The above link lists many examples of behavior like cheating and plagiarism that are violations of the academic integrit policy. The following is a non-exhaustive list of specific acts that you should NOT do because they would violate the academic integrity policy. Any of these are sufficient cause for immediate failure in the course.

-   Do not take pictures or copy exam or quiz questions and share them with other students, or share them on the internet
-   Do not give other students answers during an exam or quiz, or any other assignment that is an individual assignment
-   Do not copy work from another source and submit it as your own, this includes using tools like ChatGPT to generate text. Copying text from ChatGPT or another similar tool and submitting it as your own work violates academic integrity policies in this course.
-   Do not copy and paste text from the internet and submit it as your own words
-   Do not copy and paste text and slightly alter wording to pass the work off as your own
-   Do not hire someone else to do the coursework for you
-   Do not copy and paste text into a paraphrasing app, and then submit the output of the paraphrasing app as your own work
-   Do not copy random words from the internet that have nothing to do with the assignment and submit them as your own work.
-   Do not work on individual assignments with other students, share answers or other material, and then all hand in versions of the same thing that are slightly different.
-   Do not plagiarize yourself by submitting work that you have previously completed in another class.

### Mandate to report violations

If a faculty member suspects a violation of academic integrity and, upon investigation, confirms that violation, or if the student admits the violation, the faculty member MUST report the violation. Students should be aware that faculty may use plagiarism detection software.

There is no excuse for cheating. Students who are caught cheating may receive a failing grade for the entire course. All students who violate the academic integrity will receive a Faculty Action Report, which will go on their personal file at the Academic Integrity Office.

## The Rights of Undocumented Students

As an educator, I support the rights of undocumented students to an education. For resources and support, please visit Brooklyn College’s Immigrant Student Support Office located at 117 Roosevelt Hall.  You can also contact them via email at ISSO@brooklyn.cuny.edu or via phone at 718-951-5023.

## FAQ

If you have questions about the syllabus, please create a thread on the "Ask questions about the course" discussion board on Blackboard.
