---
title: "Honors project"
description: "Info and guidelines for obtaining honors credit in PSYC 2530."
author: "Matt Crump"
opengraph:
  image: 
    src: "https://www.crumplab.com/cognition/reference/figures/2530_honors.jpg"
    alt: "Logo for cognition website"
  twitter:
    card: summary
    creator: "@MattCrumpLab"
date: '`r paste("Last edited: ", lubridate::today())`'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Honors project}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page explains the honors project for this course. Students who successfully complete this project, and meet the other requirements can receive honors for this course. 

## Honors Project Overview

1. The honors project involves writing an experiment proposal to test a theoretical account of a cognitive phenomena. This is great way to develop your scientific thinking and creativity skills.
2. The honors project is due by the end of the Spring 2022 semester, May 24th.
3. Students who successfully complete the honors project, and meet the other requirements (e.g., grade of B or higher in the course, see General info below), will receive an "H" designation on their transcript for PSYC 2530. This means you completed the course with honors.
  - Any student who expects to meet the general requirements (listed below) could take the honors project. Students do not need to be in an honors academy to complete the honors project.
  - The honors project is completely optional, and not required.
  - The honors project is not graded and does not contribute toward your grade.
  - The honors project requires substantial extra work above and beyond the regular course curriculum
  - Honors projects either meet the conceptual requirements or they do not (listed below). Students who do not successfully complete an honors project will not be awarded the "H" designation for the course.
  - There are no negative consequences in the course for attempting the honors project and then deciding not to complete it.

## General info: Honors in a regular course

The 2021-2022 [undergraduate bulletin](http://www.brooklyn.cuny.edu/web/off_registrar/2021-2022_Undergraduate_Bulletin.pdf) describes that students can request to gain "Honors credit for regular course" (see page 62). The general bulletin information is reprinted below:

> Honors credit is earned by doing substantial supplementary work in an introductory or advanced course in the regular undergraduate curriculum. Students interested in honors credit must arrange with the instructor at the beginning of the semester to do an honors project in that course.

> To apply to do an honors project, students should discuss thoroughly the nature of work to be done with their instructor.

> At the end of the semester, the instructor submits the honors grade through an application on the BC WebCentral portal. Honors credit will be allowed when the final grade in the course is A+, A, B+, B, or P. Honors credit is indicated on transcripts in the form of an official transcript note.

## Honors project for PSYC 2530: An experiment proposal

The honors project for PSYC 2530 is a written experiment proposal. The purpose of the project is to propose an experiment capable of testing the predictions of an existing explanation or theory of a cognitive phenomena. This project is an opportunity to engage with scientific thinking in the domain of cognition.

More information is provided below.

### Approval

Students interested in completing the honors project need to seek approval from the instructor. Please email Matt Crump to express your interest and seek approval for your project.

Please read the conceptual requirements of the project listed below. This provides a set of instructions and expectations for the project.

To get approval for the honors project you will have to identify:

1. The cognitive phenomena that you will be investigating with your experiment proposal
2. The theory of the cognitive phenomena that you will be testing with your proposal
3. A citation or pdf to a cognitive psychology research article that shows the cognitive phenomena, and gives an example of the theory being tested.

### Due Date

The honors project is due by May 24th, 2022. Submit your proposal on blackboard.

### Proposal Length and Formatting Expectations

The minimum length is five double-spaced pages for the main body of the paper, not including title page, abstract, and references. The paper should be in APA style (see example paper at the end). 

### Conceptual Requirements

Research in cognition involves investigations of particular cognitive abilities. Researchers propose theories about how cognitive abilities work, and then they design experiments to test the predictions of the theories. 

This proposal requires the following conceptual components. These should be clearly identifiable in your paper.

1. **Identify a cognitive phenomena**: your proposal must test explanations of an existing cognitive phenomena that has been described in the cognition literature.
  - Establish what phenomena you are discussing at the beginning
  - Give examples of the phenomena from the literature
  - Cite your examples.
  
2. **Describe a testable theory of the phenomena**: your proposal will test an existing theoretical explanation of the cognitive phenomena you choose. 
  - Identify the theory, with citations
  - Explain how the theory works, along with how it has been used to explain aspects of the cognitive phenomena.
  
3. **Develop testable theoretical implications/predictions**: your proposal will describe an experiment that puts the theoretical explanation to the test. In order to do this, you need to consider the kinds of predictions that the theory does and does not make. What does the theory suggest would happen to the cognitive phenomena in scenario X? What does the theory suggest would happen in scenario Y? You should consider predictions that can be tested with scenarios you create with your experiment.

  - Describe the testable predictions or implications of theory
  - Note: these are the predictions that you will be proposing to test with your experiment.

4. **Propose an experimental manipulation to test the theoretical prediction**: Your proposal will describe an experimental manipulation to test the predictions of the theory.
  - This is a mini methods section
  - Describe your proposed methods, which should involve your proposed manipulation and your proposed measurement
  
5. **Make theoretical inferences about possible results**: This is where you describe possible results that could occur from your experiment, and how these results would relate to your theoretical predictions. 
  - If the theoretical predictions from above are true, then what data pattern would be expected in your experiment? Make sure you describe what pattern of data would be expected given the theoretical predictions
  - If the theoretical predictions are not true, then what data pattern would you expect to find? Make sure you also describe the kind of data pattern that would show the theoretical predictions to be incorrect
  
6. **Corroborate or Falsify?**: Your experiment proposal could be intended to corroborate the predictions of a theory, or to falsify predictions of a theory. Make sure you clarify what your proposal is aiming towards.
  - **Corroborating**: You should identify a prediction or implication from the theory that suggests a particular data pattern should be observed under the conditions of your proposed experiment. If you ran the experiment, and the data pattern was found to be the same as the pattern predicted by the theory, then your data would corroborate the theoretical prediction. (note: corroborating means "confirm or give support to", and if the data pattern fits then it confirms the prediction.)
  - **Falsifying**: Your experiment be intended to invalidate a theoretical prediction. For example, the theory could predict that a particular data pattern ought to occur in your experimental conditions; but, you may be interested in showing that the theoretically predicted pattern DOES NOT occur. If the pattern predicted by the theory does not occur, then your experiment may provide a means to disconfirm or falsify the theory.
  - If you want to have extra fun, then come up with multiple experiment proposals. For example, create one proposal that should corroborate the predictions of the theory, and another experiment proposal to falsify the predictions of the theory.
  
## Example honors project

This section provides an example of the steps to complete an honors project, including a complete example paper.

### Ask for Approval

If you have decided to attempt the honors project, then you first need to seek approval. If you have general questions please email the instructor. Otherwise, if you have an idea for an experiment proposal, then your email seeking approval might look like:

:::::{.card .border .border-2 .border-info}
:::: {.card-body}
**Example email**

I am interested in completing the honors project for PSYC 2530. I have read the honors project instructions, and I would like to get approval for my experiment proposal. 

Cognitive phenomena: My experiment proposal will test explanations of the repetition blindness effect (Kanwisher, 1987).

Theory: My experiment proposal will test the type-token individuation theory of the repetition blindness effect (Kanwisher, 1987).

I am including a pdf of a paper (Kanwisher, 1987) that describes the repetition blindness effect and the type-token individuation theory of that effect.

Citation: Kanwisher, N. G. (1987). Repetition blindness: Type recognition without token individuation. Cognition, 27(2), 117–143. https://doi.org/10.1016/0010-0277(87)90016-3
::::
:::::

### Getting approval

I will communicate with you over email to let you know if you are approved to go ahead with the honors project. The goal of the approval process is to make sure you have identified a cognitive phenomena and a theory from the literature that you can test in your proposal.

### Example proposal

The next step is to write your proposal. To provide an example of what I am looking for I wrote a sample honors project that meets the conceptual requirements above.

You can [download the example here](https://www.crumplab.com/cognition/honors_example/honors_example.pdf).

### Submitting your honors project

When you have completed your honors project, submit it on blackboard. Congrats!

## Brainstorming

This honors project allows you to choose a cognitive phenomena and theory that interests you. There are many to choose from. You could choose any phenomena and theory that has been discussed in the class so far, or you could find a new one by reading articles in [cognitive psychology journals](https://www.crumplab.com/cognition/articles/course_docs/resources.html). You should be able to download most articles you are interested in through the Brooklyn College library. Good luck and have fun! 














