```{r, include = FALSE}
source("global_stuff.R")
```

# What is cognition and how does it work?

## Chapter Overview

This chapter provides a broad view of some of the issues involved with describing, and tools and methods used to describe cognition and how it works. We begin to give some definition to cognition, although this definition expands across the rest of the textbook. Most of this chapter is concerned with background concepts that are important for understanding the processes by which we can create knowledge about how cognition works. This includes preliminary discussions about roles for theories and facts, philosophy of science, the scientific method and other methods for generating knowledge, and the kinds of explanations that provide more or less satisfying answers to questions about the mind.

## Taking a step back

What is cognition and how does it work? These are questions I have been wondering about ever since I started doing research into human cognition. At the moment, I (Matt Crump) am a roughly early/mid-career researcher who has been conducting research on topics in cognition since about 2000-2001, where I started as an undergraduate working in cognitive psychology labs. At that time I discovered that there was a large scientific literature on human and animal cognition that went back over a hundred years. Today, that very same literature has continued to grow and grow. Perhaps I shouldn't admit this, but even though I've dedicated over 20 years of my life to studying and contributing to this literature, I think I can safely say that I have way more questions about cognition than answers. In some sense, the more I learn about research into cognition, the less I feel I know about how cognition works. It's quite possible that I am more confused about cognitive psychology now (after 20 years as a researcher), than I was before I started! 

Maybe I shouldn't be writing this textbook, and you should instead find an "authoritative" textbook where you can trust that the author knows everything about cognition, is not confused, and is also able to compress over a hundred years of science down into engaging and readable chapters for beginners to the field. Indeed, there are many introductory textbooks to the field of Cognitive Psychology available, each offering the authors view on the field, along with their way of introducing the field to new students. So, just like those other textbooks, in this one, you will be treated to my view of cognition, and my style for presenting it to new students. The reason I am drawing attention to these issues is that there is one thing about cognition that is very clear to me: there are many different perspectives and answers to the question "what is cognition and how does it work?".

I would go so far as to say that it is a fact, in the year 2021, that even though cognitive psychology is a longstanding scientific discipline, that has been formally asking and answering questions about how the mind works for well over a hundred years; and even though there has been substantial progress in this field, there is nevertheless no emerging consensus view across researchers and labs about how cognition works. There are many labs and researchers and it is not uncommon for each lab or researcher to be researching their own unique phenomena, or forwarding their own preferred explanations and theories for the parts of cognition they are studying. I will develop the view across this textbook, that this kind of diversity is OK for the science of cognition; and, that a fully grown and well developed science of cognition will continue to have a great diversity of theories and perspectives about how cognition works. Although a common goal for many sciences is to arrive at a single unified theory that explains everything, even if this doesn't happen for cognition, I think that is OK too, because many of the possible explanations that will be generated along the way will make useful contributions to understanding cognition, even if parts of their explanations are not completely true.

### The truth, the whole truth, and nothing but the truth vs knowledge creation

The cognitive sciences are interested in understanding how cognition works, and this could mean that the whole enterprise is trying to figure out what is true about cognition and what is false. Science is a slow moving incremental process, so over the history of the cognitive sciences there have been many false starts. Some findings have been published that are hard to replicate (so they might not be real), and there are many theories about cognitive phenomena that have been proven to be false. There are also many findings that seem pretty stable, and there are good reasons to treat them as facts; and, despite the limitations of cognitive theories, there are nevertheless some very powerful ones out there that do a commendable job at explaining aspects of cognition. 

So, as a final thought before we get started, I'm going to give you a heads up about how this textbook will generally tell you about the story of cognition. One option is for me to sort through all of the published research on cognition (there are hundreds of thousands of published scientific manuscripts), pick all of the ones that are true, and then tell you only about the true things about cognition that we know to be true. Actually, I don't think this is really an option at all. So, I'm not even going to attempt anything like that. 

Instead, this textbook will tell a story about cognition that is not so obsessed with the truth, the whole truth, and nothing but the truth. I don't deny that there are so-called "truth's" about how cognition works. Most researchers, including me, accept facts like people and animals are physical beings, and that cognition somehow emerges from biological processes. From this perspective, there must be some truths about human and animal cognition because cognition must be determined by physical properties of our physiologies. Instead of telling a story about all the true things we think we know about cognition, I'm going to back up a little up and focus the story on the process by which cognitive science creates knowledge about cognition. Sometimes cognitive science produces knowledge about cognition that is not true about people or animals, but nevertheless very useful say for creating computer intelligence or other smart technology. Similarly, it will be important to recognize that much of what cognitive science has produced over its history resembles "working draft concepts" in the large scheme of things, and very rarely fundamental truths about cognition that everyone agrees on.

## What is Cognition?

So, what is cognition anyway? An everyday definition involves pretty much anything to do with how your mind works. If you are reading this, then you have cognition, and as someone with cognition, I'm sure you can form your own opinions on what counts as cognition for you. This textbook is both about cognition in this everyday sense, as well as the field of cognitive psychology and the broader cognitive sciences. These domains of academic inquiry have the goal of studying cognition from many different angles to produce knowledge about how cognition works. 

I like to think of cognition as a big list of questions about how cognitive abilities work. For example, How do you remember what you ate for breakfast? How do you remember something that happened when you were a kid? How do you learn language? How do you know how to say a sentence? How do you think your next thought? What is your imagination like? How do you learn new skills, like walking, riding a bike, playing a musical instrument, playing a sport, or a game? How do you learn new information, and how can you study more efficiently? How do you recognize peoples faces? How do you know a tree is a tree and not some other object? How do you make plans for the future? Do you have an inner voice and if so how do you use it? How do you make decisions in your daily life? What makes you prefer some music and not others? How do you control all of your body movements from moving your fingers to facial expressions? How do you pay attention to some things while ignoring others? How did you forget that phone number so fast? How did you forget what you were doing while you were in the middle of doing something? How do you learn to read? How do you know the meaning of words? How can you train your brain to get better at something? Why do you think you know a word that is just on the tip of your tongue, but yet you can't say the word, until later it pops in your head? How many memories can a person have? What does it mean to be smart? Can anyone learn anything to a high degree of skill? How do all of these cognitive abilities develop over the lifespan? How do people understand their own cognition? How do people understand other people's cognition? What about non-human animals, what kind of cognitive abilities do they have? Does my cat dream about me?

I hope you got the sense that I could have kept going with those questions, and that you could probably come with your similar kinds of questions. From my perspective, these kinds of questions are ones that cognition researchers are interested in asking and answering. 

Most of the above questions have two things in common that make them relevant to research in cognition (or they could be rephrased to have these two things). First, they are all about a kind of cognitive ability (such as being able to remember something, attend to something, read a book, hear a word, and so on). Second, they are "how" questions, and "how" questions are all about explaining how things work. Let's elaborate on both of these to begin answering "what is cognition?"

### Cognitive abilities

What is a cognitive ability, and what makes an ability a cognitive one as opposed to a regular ability? In the first textbook to coin the phrase "Cognitive Psychology" [@neisserCognitivePsychology1967], Neisser  defined cognition as "all processes by which the sensory input is transformed, reduced, elaborated, stored, recovered, and used". This is a pretty all-encompassing definition that still captures much of what cognitive scientists continue to study today. We could use Neisser's definition to give some definition to the concept of a cognitive ability. 

At the same time, I don't want to focus too much on narrowly defining cognition and what counts as cognitive abilities. We will get a better sense of what the field has studied under these terms across the chapters in the textbook. We will also see that cognitive psychologists sometimes get too hung up on making distinctions [@newellYouCanPlay1973] that can distract from the larger issues. For example, we could spend our time making a list features for what makes an ability a cognitive ability. These could include features like: involves mental effort, involves your brain, involves thinking, and so on. There will be inevitable disagreements about what features should or should not be included on the list. And, we could end up looking at lists of abilities and spend way too much time deciding how they should be categorized, rather than spending time trying to figure out how the abilities work.

### Answering How questions

It is much easier to answer a "can" question about cognition, than a "how" question. For example, can people remember information like a phone number? If you have ever remembered a phone number, then you know the answer is yes. Can you forget a phone number? Yes. We don't need the science of cognition to answer many "can"-type questions about cognitive abilities. 

"How" questions are much harder to answer. If I asked you, "how is it that you can remember a phone number?"; or, even more incredibly, "how can you remember a whole personal experience that happened to you ten years ago?", what kind of answer would be required to explain how those abilities work? What kind of answer would be satisfying to you? In my opinion, there are two big reasons why how-questions about cognition are hard to answer. First, the cognitive ability in question (remembering, learning, attending, talking etc.) is usually extremely complex involving the interaction of many parts, so it is sometimes frightening to imagine how detailed and complicated the explanation would have to be. Second, depending on who you talk to in the cognitive sciences, you will find that there are different levels and kinds of explanation; so, in addition to doing the hard work of explaining something about cognition, you will also have to do the hard work of understanding how different levels of explanations work, and make choices about the kinds of explanations that are appropriate and satisfying for the problem at hand.

## How does cognition work?

The purpose of this textbook is to provide an introduction to the ways in which the cognitive sciences have attempted to answer the question "how does cognition work?". However, before we go into the details about cognition, it is worth spending time considering some of the ways this domain of science works to generate knowledge about cognition. So, in the rest of this chapter we will consider slightly different "how" questions-- "how does research into cognition work? And, what kinds of things does it produce that are capable of telling us something about how cognition works?". This will include some discussion of the scientific method and others that are used to generate knowledge about cognition, as well as a discussion of philosophy of science that should help us better appreciate the kinds of explanations available and how well the explanations work.

Some of these topics are little bit abstract, and one of the principles of cognition that will be repeated across this textbook is that learning from examples is a really, really important aspect of cognition. So, before heading into these topics, I will first describe a famous debate in human cognition, and we will use this debate throughout this chapter as example to discuss some basic aspects of how cognition research works.

## The mental imagery debate

Close your eyes, and think about what you can see in your "mind's eye". Some people report being able to see life-like images that are extremely clear and vivid, almost as if there is no difference between what they can imagine seeing and what they can see when they are looking at something when their eyes are open. Some people report seeing less vivid mental imagery, that is more spatial in nature. For example, they could close their eyes and imagine their kitchen; but they wouldn't "see" their kitchen as it appears when they are looking at it for real; but, they would nevertheless have some spatial sense about the shape of the kitchen, and where things are stored in the kitchen. Other people report having very little to no mental imagery. 

For fun, I'll tell you what I see when I close my eyes. My eyelids, and not much else... it's pretty dark when I close my eyes. At the same, I can imagine my kitchen pretty easily, although, I wouldn't say that I "see" it very clearly, I "see" it more spatially. However, sometimes I do "see" images that are more visual, that look like things I see when I have my eyes open. Also, I've had lots of dreams that seemed very visually vivid and real, just like visual experiences appear to me in waking life. So, according to me, my mental imagery is all of the above.

### Facts and Phenomena

Let's assume for the moment that mental imagery is a real cognitive ability, even if different people experience mental imagery in different ways. How does mental imagery work? What kind of explanation would we be looking for to answer this question? What steps could we take to start answering this question? How have prior researchers tackled these questions, and what have we learned about mental imagery? These are the kinds of questions that cognitive researchers ask to make progress on answering the big questions about cognition.

In general, before progress can be made on all of those questions, one of the most important first steps is to collect information about the features or facts about a phenomena like mental imagery. In other words, we are often looking for an explanation to explain the facts, or things we know to be true, about a cognitive phenomena. If we didn't have any facts, there wouldn't be much to explain. So, how do we get facts that we can trust about a phenomena like mental imagery?

I chose mental imagery as an example cognitive ability because it exemplifies some of the difficulties with getting solid facts about cognition. Mental imagery in particular is a subjective phenomena, which means that individuals have their own experience of their own mind, and it is difficult for anyone else to know for sure what it is going on in someone else's mind. 

Despite the difficulties about obtaining truly objective facts about subjective experiences like mental imagery, let's review two methods that have been used in the past to collect information about mental imagery, these include subjective report and various kinds of experimental methods involving attempts at objective measurements.

### Methods of Introspection and Subjective report

Considering that mental imagery is something that concerns people's minds, and even your own mind, it seems fairly straightforward that you could introspect and think about your own mental imagery, and also ask other people about their mental imagery and find out what they say. Thinking about your own cognition, and asking people about their own cognition are two good places to start when trying to gather information about cognitive abilities. Introspection is...

Subjective report is... because we are asking people to report or tell something about a subjective experience they have.

### Galton's Statistics of mental imagery

One of the first attempts at studying mental imagery was by Sir Francis Galton [@galtonStatisticsMentalImagery1880]. In his paper on "Statistics of mental Imagery", Galton set out to "to define the different degrees of vividness with which different persons have the faculty of recalling familiar scenes under the form of mental pictures, and the peculiarities of the mental visions of different persons." How did Galton go about doing this?

#### Galton's Method of Subjective Report

Galton basically went around town and asked people he knew to respond to questions like this:

---

"Before addressing yourself to any of the Questions on the opposite page, think of some definite object -- suppose it is your breakfast-table as you sat down to it this morning -- and consider carefully the picture that rises before your mind's eye. [p. 302]

1. Illumination. -- Is the image dim or fairly clear? Is its brightness comparable to that of the actual scene ?
2. Definition. -- Are all the objects pretty well defined at the same time, or is the place of sharpest definition at any one moment more contracted than it is in a real scene?
3. Colouring. -- Are the colours of the china, of the toast, bread-crust, mustard, meat, parsley, or whatever may have been on the table, quite distinct and natural?"

---

#### Galton's results

Then, Galton recorded the answers that people gave and tried to make sense of them. Here are some the answers from "100 men, at least half of whom are distinguished in science or in other fields of intellectual work." (reprinted from his original manuscript):

---

*Cases where the faculty is very high.*

1. Brilliant, distinct, never blotchy.

2. Quite comparable to the real object. I feel as though I was dazzled, e.g., when recalling the sun to my mental vision.

3. In some instances quite as bright as an actual scene.

*Cases where the faculty is mediocre.* 

46. Fairly clear and not incomparable in illumination with that of the real scene, especially when I first catch it. Apt to become fainter when more particularly attended to.

47. Fairly clear, not quite comparable to that of the actual scene. Some objects are more sharply defined than others, the more familiar objects coming more distinctly in my mind.

48. Fairly clear as a general image; details rather misty.

*Cases where the faculty is at the lowest.*

89. Dim and indistinct, yet I can give an account of this morning's breakfast table; -- split herrings, broiled chickens, bacon, rolls, rather light coloured marmalade, faint green plates with stiff pink flowers, the girls' dresses, &c., &c. I can also tell where all the dishes were, and where the people sat (I was on a visit). But my imagination is seldom pictorial except between sleeping and waking, when I sometimes see rather vivid forms.

94. I am very rarely able to recall any object whatever with any sort of distinctness. Very occasionally an object or image will recall itself, but even then it is more like a generalised image than an individual image. I seem to be almost destitute of visualising power, as under control.

100. My powers are zero. To my consciousness there is almost no association of memory with objective visual impressions. I recollect the breakfast table, but do not see it.

---

#### Galton's conclusion

Before considering Galton's conclusion, consider what he could have found, and what he might have concluded instead. For example, if everyone has the same kind of vivid visual mental imagery, he could have found very different subjective reports. In this case, everybody might have said that they have very strong and vivid visualizing powers. But, it turns out, this is not what people said. Instead, Galton's major conclusion and discovery was evidence for a wide variety of individual differences in mental imagery. Some people reported having very strong powers of mental visualization, some people reported having medium abilities, and other people reported having essentially no abilities to visualize anything in their mind's eye at all.

If we are attempting to explain a cognitive ability like mental imagery, and Galton's results provide facts that we can trust, then the task of explaining mental imagery just got a little bit harder. For example, not only do we have to explain how people could visualize a picture in their minds eye, we also have to explain the facts that some people may do this differently, and some people may not be able to do it at all. This is a good example of the increasing complexity that comes along with the research process of gathering facts about a phenomena: asking questions uncovers more facts that raise more questions and require even more explanation.

#### Limitations with Galton's method

Galton argued that his methods were useful and appropriate to the task of measuring people's mental imagery abilities, but these methods also have many shortcomings that could easily invalidate all of the results. For example, what if everybody that Galton talked to lied about their mental imagery? In this case, none of Galton's results would be meaningful with respect to understanding mental imagery. Similarly, how accurate are people at describing their own mental imagery? If people are not very accurate, then their descriptions will not be very meaningful for describing their actual experiences. Or, what if people are having the same kinds of subjective mental imagery experiences, but they just use different words to describe those experiences. And, of course, maybe everybody was telling the truth and there really are big differences in mental imagery across people. 

One big issue here for establishing facts about mental imagery, is that the internal experience of mental imagery is not easy for other people to observe directly. In other domains of inquiry, direct observation can help people quickly establish a set of agreed upon facts. For example, a group of geologists can all look and point at a rock formation, and agree that the rock formation is there, and then proceed to further inspect and measure the rock formation to gather more directly observable facts about it. Galton's method of subjective report does have some directly observable measurements, such as the words that people said about their mental imagery; but, people's verbal statements are at best an indirect attempt to communicate an experience, and do not provide an objective lens for other observers to directly view the experience itself.

If it is not possible to establish objective facts about something subjective like mental imagery, how could we possibly hope to explain those facts given that we may not be able to agree on what the facts are in the first place!?! This is undoubtedly a challenge, and there many tools and methods that cognitive researchers have developed since Galton to help make progress on the issues. One trick is to see if the results are reproducible over time with different people.

### Aphantasia and Hyperphantasia

It is worth mentioning that much of Galton's original findings seem to hold up over time; although, perhaps surprisingly, until very recently almost no research on the vividness of mental imagery has occurred since Galton. What does the recent research show? In 2010, Zeman and colleagues reported a case of a patient with "imagery generation disorder" [@zemanLossImageryPhenomenology2010], which also received some attention in the media. Several people who heard about the finding contacted the researchers to let them know that they also had no visual imagery. This led the research group to begin examining these claims in more detail. In 2015 [@zemanLivesImageryCongenital2015], they decided to do something very similar to what Galton did; namely, ask people questions about the vividness of their mental imagery. However, instead of asking people to visualize their breakfast table (what Galton did), they used a questionnaire developed to assess the vividness of visual imagery [@marksVisualImageryDifferences1973]. They gave the questionnaire to the people who claimed they had no visual imagery, and perhaps not surprisingly, their answers to the questionnaire suggested this small group of people (about 20) had little to no visual imagery. Additionally, to breath a little new air into this research topic, they coined the term "aphantasia" to describe the condition of having little to no mental imagery.

More recently, Zeman and colleagues have continued in the tradition of Galton, and had many more people fill out questionnaires about the vividness of their mental imagery. And, just like Galton, they have found extreme differences in reported abilities. So, in addition to more reports of people with "aphantasia" who say they have little to no mental imagery, there are also people who report "hyperphantasia", or extremely vivid mental imagery. Some of the claims are really quite extraordinary. For example, in a New York Times article from a  few days ago [@zimmerManyPeopleHave2021], cognitive neuroscientist Joel Pearson claimed that 'hyperphantasia could go far beyond just having an active imagination...and that “People watch a movie, and then they can watch it again in their mind, and it’s indistinguishable.”'

I can't replay a whole movie in my head and have it be identical to what happened when I watched the movie in real life. That is pretty incredible. From my perspective, this claim is so incredible that I have some doubts about whether the person that claimed this ability is actually telling the truth, or perhaps exaggerating their ability a little bit. If there was some way to objectively know for sure that somebody was able to replay a whole movie in their mind, that would certainly be very interesting, and it would firmly establish this form of extremely powerful visual imagery as a cognitive ability that is need of explanation. 

Although I am skeptical that there are people out there that can replay entire movies in their head, there is no shortage of some people accomplishing astounding, and objectively verifiable feats of cognition. For example, among other impressive feats, Daniel Tammet [@DanielTammet2021] is famous for breaking the European record for correctly reciting from memory, the first 22,514 digits of the number pi. So, if Daniel Tammet can accurately "replay" the digits of pi in his mind for five hours, maybe it is not so strange that someone else can rewatch a whole movie in their head. Again, the role of direct observation comes into play for lending support to an extraordinary claim. The fact that Daniel could say the digits of pi out loud for other observers to hear, under controlled conditions (where those observers could verify he wasn't cheating somehow), makes it easier to believe that Daniel's ability is real. Similarly, if there were more direct methods to test claims about extreme differences in mental imagery abilities, this would lend more support to those extraordinary claims.

Notice, in terms of mental imagery, we are still talking about establishing facts about mental imagery, and we haven't even begun to consider how to explain these facts and come up with an account of how mental imagery works.

- what did galton do.
- introspect to come up with general features
- asked people about what mental imagery is like for them
- put the answers into categories and counted how often certain types of reports happen
- major conclusion there is some variation

Skip to to now...and modern aphantasia research...rediscovery of Galton...similar findings based on subjective report.

### Issues with interpretation

People could be lying

People could be inaccurate at describing their own subjective experience...might say things are different, but they actually arent' different

claims not independently verifiable by other objective means.



## Creating Generalizable knowledge

data points and shapes to explain them

### Scientific Method

### Subjective consensus

## Philosophy of Science

### popper and falsificationism

### transcendental realism

## Questions to keep in mind as you learn about cognition

What are the goals of the cognitive sciences and research in cognitive psychology? Who has been involved in setting those goals, are the goals useful, and what goals are being missed? What kind of questions about cognition have already been asked  by researchers? What were the scientific as well as social-historical reasons for why those researchers asked those questions? What answers were found, and how were they informative or not informative about how cognition works? How do the measurements and tools that researchers use to ask questions influence the kind of picture they build about how cognition works. What kinds of questions about cognition are not being asked that should be asked? Why are they not being asked? Should society invest in cognitive research? Are there research questions that should not be asked because the return on investment would not be very high? How should society decide whether or not to proceed with different kinds of research? Should research be done only if it has an applied benefit to society?


<!--


Let me consider some explanations for the fact that I can remember my own phone number. How can I do this? Let's try this explanation on for size: I have a memory system in my brain, and I put my phone number into my memory system, and that's why I can remember my phone number. 

I personally don't find that explanation very satisfying. That story doesn't tell me what a memory system is, how it works, how my brain accomplishes the job of this memory system, or how I do something like put a phone number in there and get it out again. That explanation raised more questions that it answered.

As we will see later in the chapters on memory research, sometimes we will encounter explanations that are not too different from the above. For example, one might explain the ability to hold on to a phone number in your head for a couple seconds (before forgetting it) in terms of putting the phone number into a short term memory system that is only capable of holding information for a limited amount of time. Alternatively, the ability to remember an event from ten years ago could be explained by a different kind of memory system, like a long term memory system that is capable of holding information for a long period of time. These explanations aren't too different from the one above because they sidestep most of the explanatory work. For example, how does the short term memory system work? How does the long-term memory system work?


Even if you haven't learned much about cognitive psychology, you may have heard about the concepts of short term memory and long term memory. 

I'm bringing these concepts up to raise a point about how explanations are forwarded in cognitive research. 

If we have evidence that people can remember some things for a little bit of time, and other things for a long time; this kind of evidence could potentially by explained by two different kinds of systems that allow people to remember things. One system for a short amount of time, and another of a long amount of time. However, it is extremely important to recognize that there ar


For the record, I wouldn't count the above as an explanation at all, instead rather than explaining how I remember a phone number, I brought a few other ideas into the mix and




As a result, cognition as science has progressed somewhat differently from other sciences. 

Before we really get started, there are several reasons why it is important to recognize that there are a diversity of views on cognition. 

Claims vs reality

Theory, phenomena







Over the course of the textbook some of the reasons I am confused will hopefully become more clear. However, I'm admitting to


that I come to understand how research in



What is my "framework for presenting cognition?

Claims about cognition: making them and evaluating

Theories and explanation

Abilities vs process-based explanations

The tools you use shape the picture you draw...

Cognition is a diverse body of research where people have applied to tools of measurment to answer questions about cognition. The present landscape and history of cognition partly depends on social historical context, individual motivations of researchers, funding agency missions, and tools used. In addition to what is normally included in "cognitive psychology", if we take a wider view, many other observations outside of lab and "scientific" domain of cognition, are and should be relevant to asking and answering questions about cognition.


NOTES:

There is a lot of research in cognition, and it doesn't all fit together in a logical, orderly fashion. The story of cognitive research is not one succesfully building cumulative knowledge with every published paper. It is much more confusing and complicated...full of interesting tidbits and even many failures.

Truth and facts vs. Theoretical Explanation and Tentative results

Cognition has no facts
Cognitive processes are not real...They are all theorized.

reality and cognition

-->

