```{r, include = FALSE}
source("global_stuff.R")
```

# Textbooks and Other Resources {.unnumbered}

This is not (yet...maybe one day who knows) a complete statistics textbook for statistics or R. It is a series of weekly exercises that could be used as labs in statistics courses for psychology students. They are aimed at initiating novice students into learning a programming environment for statistics like R, but also at using R as a teaching tool to aid conceptual understanding of statistics.

## Statistics textbooks we are using

Students taking this course at Brooklyn College are also taking a separate series of bi-weekly lectures, so they arrive in lab after having discussions and digested some readings. At the beginning of each lab I refer to the readings that have been assigned to students, which come from three different textbooks:

1. @vokeyThinkingData7th2018, [pdf available online](http://people.uleth.ca/~vokey/pdf/thinking.pdf)
2. @abdiExperimentalDesignAnalysis2009, portions may be downloadable from google scholar, otherwise try to find a printed copy somewhere.
3. @crumpAnsweringQuestionsData2018, <https://crumplab.github.io/statistics/>, and some the lab manual for R <https://crumplab.github.io/statisticsLab/>

## Other online textbooks

There are increasing numbers of excellent, free, and online resources for learning statistics and R, here are some:

1. Danielle Navarro's [Learning Statistics with R](https://learningstatisticswithr.com) and website for learning R [R for Psychological Science](https://psyr.djnavarro.net)
2. Russell Poldracks's [Statistical Thinking for the 21st Century](https://statsthinking21.org)
3. Martin Speekenbrink's [Statistics: data analysis and modelling](https://mspeekenbrink.github.io/sdam-book/), and companion R book [An R companion to Statistics: data analysis and modelling](https://mspeekenbrink.github.io/sdam-r-companion/)
4. Into python instead? Check out Todd Gureckis' [Lab in Cognition and Perception](http://gureckislab.org/courses/fall20/labincp/intro.html)
5. Looking for stats videos, check out Erin Buchanan's STATISTICS OF DOOM! on youtube: <https://www.youtube.com/channel/UCMdihazndR0f9XBoSXWqnYg>

## A longeR list

- Hadley Wickham has written several fantastic and free booksv that I keep coming back to all the time, [R for Data Science](https://r4ds.had.co.nz), [ggplot 2: elegant graphics for data analyis](https://ggplot2-book.org), [Advanced R](https://adv-r.hadley.nz), and [R packages](https://r-pkgs.org). 
- R markdown and knitr are core libraries for using R to create all sorts of reproducible documents from pdfs to websites. Here are some excellent resources:
  - <https://bookdown.org/yihui/rmarkdown/>
  - <https://bookdown.org/yihui/rmarkdown-cookbook/>
- Github got you down? Jenny Bryan has a pick me up for you <https://happygitwithr.com>
- Googling R questions can often turn up an example of someone solving your issue or a closely related one. For example, you can copy error messages and google them, or ask "how to do X in R".
- [Stackoverflow](https://stackoverflow.com) is great, Google will often take you there because someone has already asked your question, and someone else has answered, usually many people have answered your question many ways.
- Danielle Navarro recently made this website for introducing R, it's great, check it out (also made using this R markdown process): [http://compcogscisydney.org/psyr/](http://compcogscisydney.org/psyr/)
- Check out my slightly older programming book that also introduces R [https://crumplab.github.io/programmingforpsych/](https://crumplab.github.io/programmingforpsych/), actually don't do that, it's too old now and not worth it.
- Another solid and accessible resource for psyc stats using R [https://ademos.people.uic.edu/index.html](https://ademos.people.uic.edu/index.html).
- [https://cran.r-project.org/doc/contrib/Short-refcard.pdf](https://cran.r-project.org/doc/contrib/Short-refcard.pdf) This link takes you to a reference card, that shows a big long list of intrinsic r functions.
- A really great and really long list of resources for R! [https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/)
- There's a bunch of R markdown tricks right here <https://holtzy.github.io/Pimp-my-rmd/>.

